version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "No build steps required for a static HTML app"

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
